-- Migration 0026: drop the legacy WhatsApp session state machine (issue #350)
--
-- whatsapp_bot_sessions backed the inline SÍ/NO confirmation handshake
-- (ADR-004) that #349 superseded with the shared upload_batches/batch_items
-- pipeline. The table only ever held in-flight, TTL-bound confirmation state
-- (1h expiry) — nothing here is durable data worth preserving once the
-- awaiting_confirmation code path (handleTextReply, saveWhatsAppInvoice,
-- getPendingSession) is deleted from whatsapp-bot.ts. The other four
-- WhatsApp tables (contacts, pairing codes, processed messages, account
-- events) are untouched — they serve the contact directory, onboarding,
-- webhook dedup, and Meta account health, independent of this state machine.
--
-- IF EXISTS, because #363 also removed the table from schema.ts: a database
-- bootstrapped with `pnpm db:push` (ADR-003's local iteration path) never has
-- it, and a plain DROP would fail there. No CASCADE — nothing referenced this
-- table (its only FK pointed outward, to restaurants), so CASCADE could only
-- ever mask a dependency someone adds later that we would rather hear about.
DROP TABLE IF EXISTS "whatsapp_bot_sessions";