export type Bilingual = { es: string; en: string };

export const privacyMeta = {
	pageTitle: { es: 'Política de Privacidad · Mise en Place', en: 'Privacy Policy · Mise en Place' },
	back: { es: '← Volver', en: '← Back' },
	toggleLabel: { es: 'EN', en: 'ES' },
	title: { es: 'Política de Privacidad', en: 'Privacy Policy' },
	dateLine: { es: 'Última actualización: 1 de junio de 2026', en: 'Last updated: June 1, 2026' },
	prevails: { es: 'La versión en español prevalece sobre cualquier traducción.', en: 'The Spanish version prevails over any translation.' },
	contactEmail: 'privacy@mise-place.com',
	footer: {
		terms: { es: 'Términos de Servicio', en: 'Terms of Service' },
		cookies: { es: 'Política de Cookies', en: 'Cookie Policy' },
		refunds: { es: 'Reembolsos', en: 'Refunds' },
		legal: { es: 'Aviso Legal', en: 'Legal Notice' },
		home: { es: 'Inicio', en: 'Home' },
	},
};

export type PrivacySection =
	| { id: 'controller'; heading: Bilingual; lead: Bilingual; text: Bilingual }
	| { id: 'dataCollected'; heading: Bilingual; items: { term: Bilingual; text: Bilingual }[] }
	| { id: 'legalBasis'; heading: Bilingual; items: { term: Bilingual; text: Bilingual }[] }
	| { id: 'subprocessors'; heading: Bilingual; intro: Bilingual; tableHead: { provider: Bilingual; fn: Bilingual; country: Bilingual }; rows: { provider: Bilingual; fn: Bilingual; country: Bilingual }[] }
	| { id: 'transfers'; heading: Bilingual; text: Bilingual }
	| { id: 'retention'; heading: Bilingual; items: Bilingual[] }
	| { id: 'rights'; heading: Bilingual; introPre: Bilingual; introPost: Bilingual; items: { term: Bilingual; text: Bilingual; emphasis?: Bilingual }[]; outroPre: Bilingual; outroStrong: Bilingual; outroPost: Bilingual }
	| { id: 'cookies'; heading: Bilingual; paragraphs: Bilingual[]; linkPre: Bilingual; linkText: Bilingual; linkPost: Bilingual }
	| { id: 'security'; heading: Bilingual; text: Bilingual }
	| { id: 'contact'; heading: Bilingual; textPre: Bilingual };

export const privacySections: PrivacySection[] = [
	{ id: 'controller', heading: { es: '1. Responsable del tratamiento', en: '1. Data controller' }, lead: { es: 'Mise en Place SL', en: 'Mise en Place SL' }, text: { es: ' (en adelante, "nosotros", "la Empresa") es el responsable del tratamiento de los datos personales recogidos a través de la plataforma Mise en Place (mise-place.com).', en: ' (hereinafter "we", "the Company") is the controller of the personal data collected through the Mise en Place platform (mise-place.com).' } },
	{ id: 'dataCollected', heading: { es: '2. Datos que recopilamos', en: '2. Data we collect' }, items: [{ term: { es: 'Datos de cuenta:', en: 'Account data:' }, text: { es: ' dirección de correo electrónico, nombre y contraseña cifrada.', en: ' email address, name and encrypted password.' } }, { term: { es: 'Datos del negocio:', en: 'Business data:' }, text: { es: ' albaranes e información de proveedores que tú mismo subes.', en: ' invoices, delivery notes and supplier information that you upload yourself.' } }, { term: { es: 'Datos de uso:', en: 'Usage data:' }, text: { es: ' registros de acceso, identificadores de sesión, métricas de rendimiento anónimas.', en: ' access logs, session identifiers, anonymous performance metrics.' } }, { term: { es: 'Datos de pago:', en: 'Payment data:' }, text: { es: ' procesados directamente por Stripe; nosotros no almacenamos datos de tarjeta.', en: ' processed directly by Stripe; we do not store card data.' } }] },
	{ id: 'legalBasis', heading: { es: '3. Base legal del tratamiento', en: '3. Legal basis for processing' }, items: [{ term: { es: 'Ejecución de contrato', en: 'Performance of a contract' }, text: { es: ' (Art. 6.1.b RGPD): prestación del servicio contratado.', en: ' (Art. 6.1.b GDPR): provision of the contracted service.' } }, { term: { es: 'Interés legítimo', en: 'Legitimate interest' }, text: { es: ' (Art. 6.1.f RGPD): seguridad, prevención de fraude y mejora del servicio.', en: ' (Art. 6.1.f GDPR): security, fraud prevention and service improvement.' } }, { term: { es: 'Cumplimiento de obligación legal', en: 'Compliance with a legal obligation' }, text: { es: ' (Art. 6.1.c RGPD): conservación de registros contables.', en: ' (Art. 6.1.c GDPR): retention of accounting records.' } }] },
	{ id: 'subprocessors', heading: { es: '4. Sub-encargados del tratamiento (DPA)', en: '4. Sub-processors (DPA)' }, intro: { es: 'Para prestar el servicio, compartimos datos con los siguientes sub-encargados:', en: 'To provide the service, we share data with the following sub-processors:' }, tableHead: { provider: { es: 'Proveedor', en: 'Provider' }, fn: { es: 'Función', en: 'Function' }, country: { es: 'País', en: 'Country' } }, rows: [{ provider: { es: 'Railway Corporation', en: 'Railway Corporation' }, fn: { es: 'Base de datos y autenticación', en: 'Database and authentication' }, country: { es: 'Sudeste asiático', en: 'Southeast Asia' } }, { provider: { es: 'Google LLC (Gemini API)', en: 'Google LLC (Gemini API)' }, fn: { es: 'Extracción de datos de albaranes mediante IA', en: 'AI-based invoice data extraction' }, country: { es: 'EE.UU. (cláusulas contractuales tipo)', en: 'USA (standard contractual clauses)' } }, { provider: { es: 'Stripe Inc.', en: 'Stripe Inc.' }, fn: { es: 'Procesamiento de pagos', en: 'Payment processing' }, country: { es: 'EE.UU. (cláusulas contractuales tipo)', en: 'USA (standard contractual clauses)' } }, { provider: { es: 'Sentry (Functional Software)', en: 'Sentry (Functional Software)' }, fn: { es: 'Monitorización de errores', en: 'Error monitoring' }, country: { es: 'EE.UU. (cláusulas contractuales tipo)', en: 'USA (standard contractual clauses)' } }, { provider: { es: 'Cloudflare, Inc.', en: 'Cloudflare, Inc.' }, fn: { es: 'Protección antibot de los formularios públicos (Turnstile)', en: 'Anti-bot protection on public forms (Turnstile)' }, country: { es: 'EE.UU. (cláusulas contractuales tipo)', en: 'USA (standard contractual clauses)' } }] },
	{ id: 'transfers', heading: { es: '5. Transferencias internacionales', en: '5. International transfers' }, text: { es: 'Los proveedores estadounidenses mencionados anteriormente están sujetos a las cláusulas contractuales tipo (CCT) aprobadas por la Comisión Europea, garantizando un nivel de protección equivalente al RGPD.', en: 'The US providers mentioned above are subject to the standard contractual clauses (SCC) approved by the European Commission, ensuring a level of protection equivalent to the GDPR.' } },
	{ id: 'retention', heading: { es: '6. Conservación de datos', en: '6. Data retention' }, items: [{ es: 'Datos de cuenta: hasta la eliminación de la cuenta + 30 días de retención para reversión.', en: 'Account data: until account deletion + 30 days of retention for reversal.' }, { es: 'Albaranes y datos financieros: 5 años desde la fecha del documento (obligación legal contable).', en: 'Invoices and financial data: 5 years from the document date (legal accounting obligation).' }, { es: 'Registros de auditoría: 5 años.', en: 'Audit logs: 5 years.' }, { es: 'Datos de sesión y logs: 90 días.', en: 'Session data and logs: 90 days.' }] },
	{ id: 'rights', heading: { es: '7. Tus derechos (RGPD)', en: '7. Your rights (GDPR)' }, introPre: { es: 'Puedes ejercer los siguientes derechos enviando un correo a ', en: 'You may exercise the following rights by sending an email to ' }, introPost: { es: ':', en: ':' }, items: [{ term: { es: 'Acceso (Art. 15):', en: 'Access (Art. 15):' }, text: { es: ' obtener una copia de tus datos. Disponible en ', en: ' obtain a copy of your data. Available under ' }, emphasis: { es: 'Ajustes → Exportar mis datos', en: 'Settings → Export my data' } }, { term: { es: 'Rectificación (Art. 16):', en: 'Rectification (Art. 16):' }, text: { es: ' corregir datos inexactos.', en: ' correct inaccurate data.' } }, { term: { es: 'Supresión (Art. 17):', en: 'Erasure (Art. 17):' }, text: { es: ' solicitar la eliminación de tu cuenta y datos. Disponible en ', en: ' request the deletion of your account and data. Available under ' }, emphasis: { es: 'Ajustes → Eliminar cuenta', en: 'Settings → Delete account' } }, { term: { es: 'Portabilidad (Art. 20):', en: 'Portability (Art. 20):' }, text: { es: ' recibir tus datos en formato JSON estructurado.', en: ' receive your data in structured JSON format.' } }, { term: { es: 'Oposición (Art. 21):', en: 'Objection (Art. 21):' }, text: { es: ' oponerte al tratamiento basado en interés legítimo.', en: ' object to processing based on legitimate interest.' } }], outroPre: { es: 'Responderemos en el plazo máximo de 30 días. Tienes derecho a presentar una reclamación ante la ', en: 'We will respond within a maximum of 30 days. You have the right to lodge a complaint with the ' }, outroStrong: { es: 'AEPD', en: 'AEPD' }, outroPost: { es: ' (www.aepd.es).', en: ' (www.aepd.es).' } },
	{ id: 'cookies', heading: { es: '8. Cookies', en: '8. Cookies' }, paragraphs: [{ es: 'Usamos cookies estrictamente necesarias para mantener tu sesión autenticada. No empleamos cookies de seguimiento ni publicidad de terceros.', en: 'We use strictly necessary cookies to keep your session authenticated. We do not use third-party tracking or advertising cookies.' }, { es: 'Si llegas a la lista de espera o al registro a través de un enlace de campaña (por ejemplo, con parámetros utm_source o utm_campaign), guardamos esa procedencia en una cookie propia ("mep_attr") durante un máximo de 30 días, solo para saber qué mensaje o canal funciona. Esa cookie solo se escribe si la aceptas en el aviso de cookies; si la rechazas no se crea y, si ya existía, se borra. No se comparte con terceros ni se usa para seguirte por otros sitios.', en: 'If you reach the waitlist or sign-up page through a campaign link (for example, with utm_source or utm_campaign parameters), we store that origin in a first-party cookie ("mep_attr") for up to 30 days, solely to see which message or channel worked. That cookie is written only if you accept it in the cookie notice; if you decline it is not created and any existing one is deleted. It is not shared with third parties or used to track you across other sites.' }], linkPre: { es: 'El detalle completo de cada cookie está en la ', en: 'The full detail of every cookie is in the ' }, linkText: { es: 'Política de Cookies', en: 'Cookie Policy' }, linkPost: { es: '.', en: '.' } },
	{ id: 'security', heading: { es: '9. Seguridad', en: '9. Security' }, text: { es: 'Todos los datos se transmiten cifrados mediante TLS 1.2+. Las contraseñas se almacenan con hash bcrypt. El acceso a los datos de producción está restringido mediante roles y auditoría.', en: 'All data is transmitted encrypted via TLS 1.2+. Passwords are stored with bcrypt hashing. Access to production data is restricted through roles and auditing.' } },
	{ id: 'contact', heading: { es: '10. Contacto', en: '10. Contact' }, textPre: { es: 'Para cualquier cuestión sobre privacidad: ', en: 'For any privacy-related matter: ' } },
];
